name: AdventOfCode2018
description: Solutions for Advent of Code 2018.
version: 0.0.1

environment:
  sdk: "^3.5.0"

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
